name: Build Application on Windows

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Create virtualenv
      run: |
        python -m venv venv
        .\venv\Scripts\activate

    - name: Install dependencies
      run: |
        .\venv\Scripts\activate
        pip install -r requirements.txt    

    - name: Install cx_Freeze
      run: pip install cx_Freeze

    - name: Build Executable
      run: python setup.py build


    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: executable
        path: dist/
