name: flyday Release

on: 
    push:
       tags:
       - 'Flyday-v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.2'
        
    - name: Install dependencies
      run: |
        python -m pip install    
        pip install -r requirements.txt
    
    - name: Build Executable
      run: python setup.py build

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: executable
        path: dist/flyday/

    - name: List contents of the dist directory
      run: ls dist/    

    - name: Zip the Build
      run: |
        Compress-Archive -Path dist/flyday -DestinationPath Flyday.zip

      
    - name: Create Release and Upload Release Asset
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        #tag_name: ${{ github.ref }}
        #name: ${{ github.ref }}
        body: TODO New Release.
        #body_path: CHANGELOG.txt
        draft: false
        prerelease: false
        files: |
          Flyday.zip
          LICENSE 
      
